package com.wximp.mintweather.sqlite;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by smile on 2016/12/14.
 */

public class MySqliteOpenhelper extends SQLiteOpenHelper {
    public MySqliteOpenhelper(Context context) {
        super(context, "mintwt.db", null, 1);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        sqLiteDatabase.execSQL("create table city (_id varchar(20) primary key,cn_name varchar(20),en_name varchar(30),father varchar(20))");
        sqLiteDatabase.execSQL("insert into city values('TV9JG0M1S9QU','阿里','Ali','西藏')" +
                ",('TVPNW82QN57R','日喀则','Rikaze','西藏')" +
                ",('TXN08CQCQM63','喀什','Kashi','新疆')" +
                ",('TXN1VQC3C8ST','阿图什','Atushi','新疆')" +
                ",('TY8G4T7ZWVX1','和田','Hetian','新疆')" +
                ",('TZ1Y9TFKC7BS','阿拉尔','Alaer','新疆')" +
                ",('TZ344WFBDS60','阿克苏','Akesu','新疆')" +
                ",('TZCCF7RKT36V','伊宁','Yining','新疆')" +
                ",('TZFR7TC93WEK','博乐','Bole','新疆')" +
                ",('TZMM87UXBKRG','库尔勒','Kuerle','新疆')" +
                ",('TZVHJ8T4HQ93','石河子','Shihezi','新疆')" +
                ",('TZXKM4G9GS71','吐鲁番','Tulufan','新疆')" +
                ",('TZY33C4YJBP3','乌鲁木齐','Wulumuqi','新疆')" +
                ",('TZY46T9GJ6Y0','昌吉','Changji','新疆')" +
                ",('TZY7200FWT0M','五家渠','Wujiaqu','新疆')" +
                ",('VB71BQ84QPSS','塔城','Tacheng','新疆')" +
                ",('VBH77M0RQ24G','克拉玛依','Kelamayi','新疆')" +
                ",('VBW8JQY63YDB','阿勒泰','Aletai','新疆')" +
                ",('W5ZTMB87F1X8','景洪','Jinghong','云南')" +
                ",('W6ZZU0QTK2SN','西沙','Xisha','海南')" +
                ",('W7JZGDR3YYTF','三亚','Sanya','海南')" +
                ",('W7MDSJR4TMK4','乐东','Ledong','海南')" +
                ",('W7MFU4Y12VWZ','五指山','Wuzhishan','海南')" +
                ",('W7MHXVJCW6NC','东方','Dongfang','海南')" +
                ",('W7MT92RG3HJD','昌江','Changjiang','海南')" +
                ",('W7MV6SENCGG4','白沙','Baisha','海南')" +
                ",('W7MZJ3D2NP9X','儋州','Danzhou','海南')" +
                ",('W7Q1BR3PE78W','保亭','Baoting','海南')" +
                ",('W7Q1PZC6KCFW','陵水','Lingshui','海南')" +
                ",('W7QDBNQVFQN8','万宁','Wanning','海南')" +
                ",('W7QH70RCB3PE','琼中','Qiongzhong','海南')" +
                ",('W7QQ1QHQ7VWQ','屯昌','Tunchang','海南')" +
                ",('W7QT9B3G3S46','琼海','Qionghai','海南')" +
                ",('W7QZ1QFP50HH','文昌','Wenchang','海南')" +
                ",('W7TCRF6D3JPS','临高','Lingao','海南')" +
                ",('W7UR7MB3QQDU','崇左','Chongzuo','广西')" +
                ",('W7V53W659VPW','防城港','Fangchenggang','广西')" +
                ",('W7VD5N6F061Q','北海','Beihai','广西')" +
                ",('W7VHZEYSJ2W6','钦州','Qinzhou','广西')" +
                ",('W7W0PPEX9F8F','澄迈','Chengmai','海南')" +
                ",('W7W2N6K8F64J','定安','Dingan','海南')" +
                ",('W7W3YQKE4QDH','海口','Haikou','海南')" +
                ",('W7Y3P046TR7U','湛江','Zhanjiang','广东')" +
                ",('W7YGK0CKZKF9','茂名','Maoming','广东')" +
                ",('W7ZSKJM3GP7Z','阳江','Yangjiang','广东')" +
                ",('W982Y5WFG81G','南沙','Nansha','海南')" +
                ",('WDC336NBG99F','中沙','Wuzhishan','海南')" +
                ",('WEBY8Q5HHUCU','珠海','Zhuhai','广东')" +
                ",('WHPG4ZZB3XSN','普洱','Puer','云南')" +
                ",('WHPPV7HP148U','临沧','Lincang','云南')" +
                ",('WHQ5514S00XF','德宏','Dehong','云南')" +
                ",('WHQWBSVQS7RS','保山','Baoshan','云南')" +
                ",('WHW713U75VQ2','怒江','Nujiang','云南')" +
                ",('WHX38U36B3BU','大理','Dali','云南')" +
                ",('WHYYKDR3D2H0','香格里拉','Xianggelila','云南')" +
                ",('WHZ2BV37270V','丽江','Lijiang','云南')" +
                ",('WJ1Q3KPFD1QS','山南','Shannan','西藏')" +
                ",('WJ2B9TWGFBT5','拉萨','Lasa','西藏')" +
                ",('WJ70G7N4S3H0','林芝','Linzhi','西藏')" +
                ",('WJ97P4G263RF','那曲','Naqu','西藏')" +
                ",('WJT157H36HS5','昌都','Changdu','西藏')" +
                ",('WJUGXXRYCVG7','玉树','Yushu','青海')" +
                ",('WJX5GH5PYG5R','甘孜','Ganzi','四川')" +
                ",('WK1KZS3MC5U1','红河','Honghe','云南')" +
                ",('WK2FT8F9H0YR','玉溪','Yuxi','云南')" +
                ",('WK2NQUD6QD0J','楚雄','Chuxiong','云南')" +
                ",('WK3N92NQV6RQ','昆明','Kunming','云南')" +
                ",('WK4HUQ2S15F0','文山','Wenshan','云南')" +
                ",('WK5ZFNY7D4FJ','百色','Baise','广西')" +
                ",('WK6WEJ9VE4V7','兴义','Xingyi','贵州')" +
                ",('WK8R4WWPXZ1K','攀枝花','Panzhihua','四川')" +
                ",('WK9C440U729C','曲靖','Qujing','云南')" +
                ",('WKBWQZEYXGPF','凉山','Liangshan','四川')" +
                ",('WKCG2PQ8G1M2','昭通','Zhaotong','云南')" +
                ",('WKDXH1Q2BNXZ','水城','Shuicheng','贵州')" +
                ",('WKEM6FWMMFWJ','安顺','Anshun','贵州')" +
                ",('WKEZD7MXE04F','贵阳','Guiyang','贵州')" +
                ",('WKFG79YD1BCG','毕节','Bijie','贵州')" +
                ",('WKJ1F428HH2F','南宁','Nanning','广西')" +
                ",('WKJGQJ0R3057','贵港','Guigang','广西')" +
                ",('WKJWVXFV72X7','来宾','Laibin','广西')" +
                ",('WKKUE0QPVT8X','河池','Hechi','广西')" +
                ",('WKMF3VJHWB9X','柳州','Liuzhou','广西')" +
                ",('WKN2DZXM71F0','玉林','Yulin','广西')" +
                ",('WKPDMK3Y8JWT','云浮','Yunfu','广东')" +
                ",('WKPGPK45UZQM','肇庆','Zhaoqing','广东')" +
                ",('WKPJS42KFVJX','梧州','Wuzhou','广西')" +
                ",('WKQRV6P6WM81','桂林','Guilin','广西')" +
                ",('WKR6FMS0Z3UW','贺州','Hezhou','广西')" +
                ",('WKSMQWM9VDFV','都匀','Duyun','贵州')" +
                ",('WKSZ0YTRER5H','凯里','Kaili','贵州')" +
                ",('WKUJ8GKSN3ZC','遵义','Zunyi','贵州')" +
                ",('WKVTSQQ2WQS8','铜仁','Tongren','贵州')" +
                ",('WKXQ7GRJYT07','永州','Yongzhou','湖南')" +
                ",('WKYHZ4GWCU8B','怀化','Huaihua','湖南')" +
                ",('WKZ7089YZ20M','邵阳','Shaoyang','湖南')" +
                ",('WKZTU85FVNSV','娄底','Loudi','湖南')" +
                ",('WM34XCDQ1VND','雅安','Yaan','四川')" +
                ",('WM3B1R518R80','乐山','Leshan','四川')" +
                ",('WM3FFWQTYQ52','眉山','Meishan','四川')" +
                ",('WM47STMVQSWN','宜宾','Yibin','四川')" +
                ",('WM4UPPEGCN1F','泸州','Luzhou','四川')" +
                ",('WM4WBR42NUWC','自贡','Zigong','四川')" +
                ",('WM67M75V9WZY','资阳','Ziyang','四川')" +
                ",('WM68Q2Z5FRTM','内江','Neijiang','四川')" +
                ",('WM6N2PM3WY2K','成都','Chengdu','四川')" +
                ",('WM7B0X53DZW2','重庆','Chongqing','重庆')" +
                ",('WM7JD7CXZK37','遂宁','Suining','四川')" +
                ",('WM7RJGM47PV5','南充','Nanchong','四川')" +
                ",('WM7V66VSE5DV','广安','Guangan','四川')" +
                ",('WMB74JR8MU82','阿坝','Aba','四川')" +
                ",('WMD1P5P1QK95','德阳','Deyang','四川')" +
                ",('WMD7P0YN1CHN','绵阳','Mianyang','四川')" +
                ",('WMEVJW5E9Q66','巴中','Bazhong','四川')" +
                ",('WMFW5823J5Q2','武都','Wudu','甘肃')" +
                ",('WMG22PXN3WPT','广元','Guangyuan','四川')" +
                ",('WMMU75CW7CKH','恩施','Enshi','湖北')" +
                ",('WMN10GQZYQDK','吉首','Jishou','湖南')" +
                ",('WMNT9YCY99D6','张家界','Zhangjiajie','湖南')" +
                ",('WMPFEYKZJDQM','益阳','Yiyang','湖南')" +
                ",('WMPMM26US87X','常德','Changde','湖南')" +
                ",('WMRNSHZ87YY1','宜昌','Yichang','湖北')" +
                ",('WMRU9C7MH9C3','荆州','Jingzhou','湖北')" +
                ",('WMS3W5RJETCF','达州','Dazhou','四川')" +
                ",('WMUH5K1WDWZC','汉中','Hanzhong','陕西')" +
                ",('WMV9BV1YY1EC','安康','Ankang','陕西')" +
                ",('WMW7Q9T3W529','神农架','Shennongjia','湖北')" +
                ",('WMXB90VDC7PZ','荆门','Jingmen','湖北')" +
                ",('WMXY3PVX93RV','襄阳','Xiangyang','湖北')" +
                ",('WMYC8VK3H18J','十堰','Shiyan','湖北')" +
                ",('WN7RPW01FK0F','格尔木','Geermu','青海')" +
                ",('WNPK15RJ0H84','果洛','Guoluo','青海')" +
                ",('WNRW6560ZURV','海南','Hainan','青海')" +
                ",('WNTHRYRP0P8J','海西','Haixi','青海')" +
                ",('WNXF241JU7T0','海北','Haibei','青海')" +
                ",('WNZMMYCRWTUZ','张掖','Zhangye','甘肃')" +
                ",('WPDE8HGNVFWJ','哈密','Hami','新疆')" +
                ",('WPJFKJQ5BCWZ','嘉峪关','Jiayuguan','甘肃')" +
                ",('WPN41UK0D3H6','酒泉','Jiuquan','甘肃')" +
                ",('WQ1NYPBJ3BD7','合作','Hezuo','甘肃')" +
                ",('WQ2D1TXVBJ01','黄南','Huangnan','青海')" +
                ",('WQ2Y3RYEE7DY','海东','Haidong','青海')" +
                ",('WQ36SBF902FR','临夏','Linxia','甘肃')" +
                ",('WQ3V4QR6VR6G','兰州','Lanzhou','甘肃')" +
                ",('WQ5HTXNGNE1W','天水','Tianshui','甘肃')" +
                ",('WQ66KU06BHB1','定西','Dingxi','甘肃')" +
                ",('WQ6PFTTX1VY6','白银','Baiyin','甘肃')" +
                ",('WQ7F5V8HRBZU','平凉','Pingliang','甘肃')" +
                ",('WQ7SF3WEPQRU','固原','Guyuan','宁夏')" +
                ",('WQ82K43YVYU8','西宁','Xining','青海')" +
                ",('WQ8ZZ2UYK26X','武威','Wuwei','甘肃')" +
                ",('WQBEJ0TNY84M','金昌','Jinchang','甘肃')" +
                ",('WQDV3QM9ZDUM','中卫','Zhongwei','宁夏')" +
                ",('WQG80DH3X35S','吴忠','Wuzhong','宁夏')" +
                ",('WQGDF7NXZRZB','银川','Yinchuan','宁夏')" +
                ",('WQGHUSF91KWU','阿左旗','Azuoqi','内蒙古')" +
                ",('WQGTUXRECXJN','石嘴山','Shizuishan','宁夏')" +
                ",('WQH5TBCEVBMU','宝鸡','Baoji','陕西')" +
                ",('WQHG50QPMX0T','杨凌','Yangling','陕西')" +
                ",('WQJ6YY8MHZP0','西安','Xian','陕西')" +
                ",('WQJ7398FTXFD','咸阳','Xianyang','陕西')" +
                ",('WQJQWC27HZX1','铜川','Tongchuan','陕西')" +
                ",('WQJU78X3NFJU','渭南','Weinan','陕西')" +
                ",('WQKE38EK0NBP','庆阳','Qingyang','甘肃')" +
                ",('WQN0TV21C6RY','商洛','Shangluo','陕西')" +
                ",('WQNZJRJNM3JV','运城','Yuncheng','山西')" +
                ",('WQPJF7T25VCT','三门峡','Sanmenxia','河南')" +
                ",('WQPUYY7S4GV2','洛阳','Luoyang','河南')" +
                ",('WQRM38NMHR7P','临汾','Linfen','山西')" +
                ",('WQTB5QBFKYSB','延安','Yanan','陕西')" +
                ",('WQXJ2UGJEGPU','吕梁','Lvliang','山西')" +
                ",('WQY1BBWVNM4Q','榆林','Yulin','陕西')" +
                ",('WQZZWRV1BGKH','朔州','Shuozhou','山西')" +
                ",('WR5CWTXYQRVP','乌海','Wuhai','内蒙古')" +
                ",('WRHRGFQ3CQS6','临河','Linhe','内蒙古')" +
                ",('WRN16S9GJRQ1','鄂尔多斯','Eerduosi','内蒙古')" +
                ",('WRNP70PG2MPX','包头','Baotou','内蒙古')" +
                ",('WRR2Q2Z7CXWM','呼和浩特','Huhehaote','内蒙古')" +
                ",('WS02MNW64CP6','江门','Jiangmen','广东')" +
                ",('WS06YNEMPP18','佛山','Foshan','广东')" +
                ",('WS08H58U92R8','中山','Zhongshan','广东')" +
                ",('WS0E9D8WN298','广州','Guangzhou','广东')" +
                ",('WS0GHKN5ZP7T','东莞','Dongguan','广东')" +
                ",('WS0QU43YTBHW','清远','Qingyuan','广东')" +
                ",('WS10730EM8EV','深圳','Shenzhen','广东')" +
                ",('WS17E8Y5G0RU','惠州','Huizhou','广东')" +
                ",('WS1WFPCVR8WG','河源','Heyuan','广东')" +
                ",('WS2V1N2FZZ77','韶关','Shaoguan','广东')" +
                ",('WS4196CZ5GG1','汕尾','Shanwei','广东')" +
                ",('WS4UZ4EZ953Z','汕头','Shantou','广东')" +
                ",('WS4VBP4H9W1J','揭阳','Jieyang','广东')" +
                ",('WS4YTUBPDZY9','潮州','Chaozhou','广东')" +
                ",('WS6D4KH12059','梅州','Meizhou','广东')" +
                ",('WS7EMPWP7EQ3','漳州','Zhangzhou','福建')" +
                ",('WS7GQBRNR6V8','厦门','Xiamen','福建')" +
                ",('WS7NZ16DHEHU','龙岩','Longyan','福建')" +
                ",('WS86EV4EKUK4','郴州','Chenzhou','湖南')" +
                ",('WS9DZQ1QXHGR','赣州','Ganzhou','江西')" +
                ",('WSB118FZZ57Y','衡阳','Hengyang','湖南')" +
                ",('WSBQ3F31E8P0','湘潭','Xiangtan','湖南')" +
                ",('WSBQQ66C8040','株洲','Zhuzhou','湖南')" +
                ",('WSBVNTZH3M2C','萍乡','Pingxiang','江西')" +
                ",('WSCF23JCKNQJ','吉安','Jian','江西')" +
                ",('WSCQ4UBFXPTE','宜春','Yichun','江西')" +
                ",('WSCWR06PNPFU','新余','Xinyu','江西')" +
                ",('WSETKW23BDUT','三明','Sanming','福建')" +
                ",('WSFXR95RZD21','抚州','Fuzhou','江西')" +
                ",('WSKMS3KBE2JM','泉州','Quanzhou','福建')" +
                ",('WSS8S6CQZBPG','莆田','Putian','福建')" +
                ",('WSSP952Z8846','南平','Nanping','福建')" +
                ",('WSSU6EXX52RE','福州','Fuzhou','福建')" +
                ",('WSSZXXPU1B76','宁德','Ningde','福建')" +
                ",('WSVZ695PCF71','温州','Wenzhou','浙江')" +
                ",('WT029G15ETRJ','长沙','Changsha','湖南')" +
                ",('WT0RN4EKXHCD','岳阳','Yueyang','湖南')" +
                ",('WT2M09U9QEH8','潜江','Qianjiang','湖北')" +
                ",('WT2QRPRCSNKH','天门','Tianmen','湖北')" +
                ",('WT2SV8EY0D76','仙桃','Xiantao','湖北')" +
                ",('WT33C6J2C563','咸宁','Xianning','湖北')" +
                ",('WT3GC9DRC209','黄石','Huangshi','湖北')" +
                ",('WT3PBQDH23US','孝感','Xiaogan','湖北')" +
                ",('WT3Q0FW9ZJ3Q','武汉','Wuhan','湖北')" +
                ",('WT3SYNJHF48X','鄂州','Ezhou','湖北')" +
                ",('WT3TJZMB152J','黄冈','Huanggang','湖北')" +
                ",('WT47HJP3HEMP','南昌','Nanchang','江西')" +
                ",('WT50ZFRU8TYY','鹰潭','Yingtan','江西')" +
                ",('WT5CU7PJK0RS','上饶','Shangrao','江西')" +
                ",('WT5QD22W4GKR','景德镇','Jingdezhen','江西')" +
                ",('WT62ZWSX5CM0','九江','Jiujiang','江西')" +
                ",('WT7JXTC4NSMZ','安庆','Anqing','安徽')" +
                ",('WT7W3R63DQMH','池州','Chizhou','安徽')" +
                ",('WT7ZCN9UKCZS','铜陵','Tongling','安徽')" +
                ",('WT8S7Y3W2KX4','随州','Suizhou','湖北')" +
                ",('WT9NG9P4ZDHG','信阳','Xinyang','河南')" +
                ",('WTB58RQWFJC5','南阳','Nanyang','河南')" +
                ",('WTC5DEFF6TD5','驻马店','Zhumadian','河南')" +
                ",('WTCP494CDTDN','漯河','Luohe','河南')" +
                ",('WTCX2BMDDWHP','周口','Zhoukou','河南')" +
                ",('WTDUEP89WV0P','六安','Luan','安徽')" +
                ",('WTEMH46Z5N09','合肥','Hefei','安徽')" +
                ",('WTF75T383SE2','阜阳','Fuyang','安徽')" +
                ",('WTG1WKHG98G5','淮南','Huainan','安徽')" +
                ",('WTG7R0CSBHZ9','蚌埠','Bengbu','安徽')" +
                ",('WTGPMFNHZW6H','宿州','Suzhou','安徽')" +
                ",('WTHS8FW3RYBK','衢州','Quzhou','浙江')" +
                ",('WTJ3BG5J683H','丽水','Lishui','浙江')" +
                ",('WTJJ6TY7R0FK','金华','Jinhua','浙江')" +
                ",('WTK1H2DTJ1U4','黄山','Huangshan','安徽')" +
                ",('WTMDXTK6STK4','绍兴','Shaoxing','浙江')" +
                ",('WTMKQ069CCJ7','杭州','Hangzhou','浙江')" +
                ",('WTMRU3PTDC3X','湖州','Huzhou','浙江')" +
                ",('WTMYGTZ7WZMY','嘉兴','Jiaxing','浙江')" +
                ",('WTN74CS48NB0','台州','Taizhou','浙江')" +
                ",('WTQ3VZQP879N','宁波','Ningbo','浙江')" +
                ",('WTQFSTR6DMK4','舟山','Zhoushan','浙江')" +
                ",('WTS2N4R0GD1V','宣城','Xuancheng','安徽')" +
                ",('WTS4JZ3WMZMC','芜湖','Wuhu','安徽')" +
                ",('WTSK2DC1FHK3','马鞍山','Maanshan','安徽')" +
                ",('WTSPU2JCPU6T','滁州','Chuzhou','安徽')" +
                ",('WTSQQYHVQ973','南京','Nanjing','江苏')" +
                ",('WTSZNJUFDEP9','镇江','Zhenjiang','江苏')" +
                ",('WTTDPCGXTWUS','苏州','Suzhou','江苏')" +
                ",('WTTE97PU94T9','无锡','Wuxi','江苏')" +
                ",('WTTKC92GVT6S','常州','Changzhou','江苏')" +
                ",('WTTVYTY1H0HF','南通','Nantong','江苏')" +
                ",('WTUBM40RTTUB','扬州','Yangzhou','江苏')" +
                ",('WTUXK27DXN0R','淮安','Huaian','江苏')" +
                ",('WTV28G74FW3J','泰州','Taizhou','江苏')" +
                ",('WTVMWP4TCFT7','盐城','Yancheng','江苏')" +
                ",('WTW3SJ5ZBJUY','上海','Shanghai','上海')" +
                ",('WW02P7XHT0KB','平顶山','Pingdingshan','河南')" +
                ",('WW0CWDZP17BC','许昌','Xuchang','河南')" +
                ",('WW0P9B6381U6','济源','Jiyuan','河南')" +
                ",('WW0V9QP93VS8','郑州','Zhengzhou','河南')" +
                ",('WW1MBZNSXN1M','开封','Kaifeng','河南')" +
                ",('WW23BS9T8PB1','晋城','Jincheng','山西')" +
                ",('WW2835D5K7BE','焦作','Jiaozuo','河南')" +
                ",('WW2BZF5MQKGW','新乡','Xinxiang','河南')" +
                ",('WW2MYN52R11E','长治','Changzhi','山西')" +
                ",('WW372S04V500','鹤壁','Hebi','河南')" +
                ",('WW3G3XDR3729','濮阳','Puyang','河南')" +
                ",('WW3M6GBCXPV8','安阳','Anyang','河南')" +
                ",('WW42DDHQT937','亳州','Bozhou','安徽')" +
                ",('WW45ZXMVB36N','商丘','Shangqiu','河南')" +
                ",('WW511U7JJ68Q','淮北','Huaibei','安徽')" +
                ",('WW56FQXV5ZHB','徐州','Xuzhou','江苏')" +
                ",('WW5QJDVC4NKQ','枣庄','Zaozhuang','山东')" +
                ",('WW607X60CDS4','菏泽','Heze','山东')" +
                ",('WW6CSB4BQYSD','济宁','Jining','山东')" +
                ",('WW6RR5W09UKP','聊城','Liaocheng','山东')" +
                ",('WW7MBNP039PE','泰安','Taian','山东')" +
                ",('WW7WJ9SSV9R7','莱芜','Laiwu','山东')" +
                ",('WW8NMEQJCMJE','晋中','Jinzhong','山西')" +
                ",('WW8P3NH2TPDT','太原','Taiyuan','山西')" +
                ",('WW8Z267HHZ3U','阳泉','Yangquan','山西')" +
                ",('WW92M43YCQG0','邯郸','Handan','河北')" +
                ",('WW96VH3U3KG5','邢台','Xingtai','河北')" +
                ",('WWB4T4PKXRH7','忻州','Xinzhou','山西')" +
                ",('WWC2MYYCM6J5','石家庄','Shijiazhuang','河北')" +
                ",('WWDQ8KE95MGB','衡水','Hengshui','河北')" +
                ",('WWDTN3X443VR','德州','Dezhou','山东')" +
                ",('WWE0TGW4PX6N','济南','Jinan','山东')" +
                ",('WWECQQCKH37Z','淄博','Zibo','山东')" +
                ",('WWEUSKZ4K1P9','滨州','Binzhou','山东')" +
                ",('WWFJ5S4DNJ0T','保定','Baoding','河北')" +
                ",('WWG1FS318M6P','沧州','Cangzhou','河北')" +
                ",('WWGQDCW6TBW1','天津','Tianjin','天津')" +
                ",('WWH1780CEFBR','宿迁','Suqian','江苏')" +
                ",('WWHPMHEV4CS4','临沂','Linyi','山东')" +
                ",('WWHUBFTRE77P','连云港','Lianyungang','江苏')" +
                ",('WWKCX8PB3YE6','日照','Rizhao','山东')" +
                ",('WWMT5Q64CR3G','青岛','Qingdao','山东')" +
                ",('WWS8Z342UPZ7','潍坊','Weifang','山东')" +
                ",('WWSKUMUVE3TR','东营','Dongying','山东')" +
                ",('WWWM51WDH1FX','烟台','Yantai','山东')" +
                ",('WWWV6YM1F4ZV','威海','Weihai','山东')" +
                ",('WWYMRT0VRMUG','大连','Dalian','辽宁')" +
                ",('WX0S40QDCME0','大同','Datong','山西')" +
                ",('WX23MTKCJ427','集宁','Jining','内蒙古')" +
                ",('WX38NPJ1DP88','张家口','Zhangjiakou','河北')" +
                ",('WX4BZD6KEJFY','廊坊','Langfang','河北')" +
                ",('WX4FBXXFKE4F','北京','Beijing','北京')" +
                ",('WX7C5D6581T3','承德','Chengde','河北')" +
                ",('WXF9CJPWG18C','锡林浩特','Xilinhaote','内蒙古')" +
                ",('WXH13WQT7XKN','唐山','Tangshan','河北')" +
                ",('WXJ51T411GRX','秦皇岛','Qinhuangdao','河北')" +
                ",('WXJZTSCEPN4J','葫芦岛','Huludao','辽宁')" +
                ",('WXMSKZT4B3TT','朝阳','Chaoyang','辽宁')" +
                ",('WXNZM7TPVMMZ','营口','Yingkou','辽宁')" +
                ",('WXQ1U6H0VE63','锦州','Jinzhou','辽宁')" +
                ",('WXQCCV8TM5T4','盘锦','Panjin','辽宁')" +
                ",('WXQX09T2HRXX','阜新','Fuxin','辽宁')" +
                ",('WXR3Y6P2CEQ3','鞍山','Anshan','辽宁')" +
                ",('WXRDFBCXJJ8E','辽阳','Liaoyang','辽宁')" +
                ",('WXRVB9QYXKY8','沈阳','Shenyang','辽宁')" +
                ",('WXS86P4BSG4G','赤峰','Chifeng','内蒙古')" +
                ",('WXYBNKF2CT25','通辽','Tongliao','内蒙古')" +
                ",('WZ0KQ36Y0N4N','丹东','Dandong','辽宁')" +
                ",('WZ24BQQTFN10','本溪','Benxi','辽宁')" +
                ",('WZ2NM0P2XMU7','抚顺','Fushun','辽宁')" +
                ",('WZ3T3SEQVEVF','通化','Tonghua','吉林')" +
                ",('WZ3YSC05ZW82','白山','Baishan','吉林')" +
                ",('WZ809BF6B5HR','铁岭','Tieling','辽宁')" +
                ",('WZ8GZQHFH76E','辽源','Liaoyuan','吉林')" +
                ",('WZ8MTDUGMP22','四平','Siping','吉林')" +
                ",('WZC1EXZ0P9HU','长春','Changchun','吉林')" +
                ",('WZCCRENBK8PQ','吉林','Jilin','吉林')" +
                ",('WZS5FY540EQG','延吉','Yanji','吉林')" +
                ",('WZUJT5EC6FK4','牡丹江','Mudanjiang','黑龙江')" +
                ",('Y8NY1KD57NS4','乌兰浩特','Wulanhaote','内蒙古')" +
                ",('Y8P7E0F5F2QK','白城','Baicheng','吉林')" +
                ",('Y8V0J2JZ730B','海拉尔','Hailaer','内蒙古')" +
                ",('YB0B8REJKCCB','松原','Songyuan','吉林')" +
                ",('YB1UX38K6DY1','哈尔滨','Haerbin','黑龙江')" +
                ",('YB2BVPSH4JM5','大庆','Daqing','黑龙江')" +
                ",('YB2JK81THR6Z','齐齐哈尔','Qiqihaer','黑龙江')" +
                ",('YB63388P2QN8','绥化','Suihua','黑龙江')" +
                ",('YB7XT0YP7SYK','伊春','Yichun','黑龙江')" +
                ",('YBBQB6TMV95Z','大兴安岭','Daxinganling','黑龙江')" +
                ",('YBFTUGSP7QCT','黑河','Heihe','黑龙江')" +
                ",('YBJ1SQ97WHN1','鸡西','Jixi','黑龙江')" +
                ",('YBJH7VFZU4T1','七台河','Qitaihe','黑龙江')" +
                ",('YBKDQEKD30TF','佳木斯','Jiamusi','黑龙江')" +
                ",('YBKTK25TPP2R','鹤岗','Hegang','黑龙江')" +
                ",('YBM322SX2QPB','双鸭山','Shuangyashan','黑龙江')" +
                ",('WECNV8ZNE40W','香港','Hong Kong','香港')" +
                ",('WEBTFUSKS7HB','澳门','Macao','澳门')" +
                ",('WSJ89JC5P1S7','高雄','Gaoxiong','台湾')" +
                ",('WSMC3UM5YY39','台中','Taizhong','台湾')" +
                ",('WSQQMXBCC2VS','台北','Taipei','台湾');");
        sqLiteDatabase.execSQL("create table info (_id varchar(20) primary key)");


    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {

    }
}
